language: java
notifications:
  hipchat:
    rooms:
      secure: TCJDN0t8Qr1YuX+ZT/HOMvfMoENxvlXMk1YiY/eWZGd5fkl1pAVM5GOsuYwScd3qf3KKoLSmcyJD7nKN2F8b/PX7kLB6OI/qumtSwUPS3PiuUtTY3K2+dSPsA+TanMM9pz99Fs6XH9NtEDSDAfkt/erse8nLm57nJ5o9ratmnE4=
deploy:
  provider: releases
  api_key:
    secure: dTXLPL2ccrgTIajM/4dC2YzAPFh4SYDJWImpI6PDNsNqFB5RZPWX3Ql/Ch2fb0uKU+zrDFmSdH2i7ytB/3Gw18pdks4ANt1vgPF7GcuBhLmlNE79Yk46R3mXCBcP0A4Fal4i2GPK9mSX3BeHWmU9xiFgjc8NX11z+sF3ncoDR4g=
  skip_cleanup: true
  file_glob: true
  file: build/distributions/*
  on:
    repo: xebialabs-community/xld-tibcobw-plugin
    all_branches: true
    tags: true
